# MP Configuration File
# This file is used by mp.sh and the Grading System to determine environment settings.
# It will be overwritten by the TA during the Official Grading phase.

# Assignment Identifier
ASSIGNMENT="mp3"
REPOSITORY_NAME="ntuos2026-mp3"
DOCKER_IMAGE="ghcr.io/typas/mpx:ntuos2026"
ACTION_IMAGE="ghcr.io/typas/mpx:ntuos2026"

# Homework Deadline (ISO 8601)
DEADLINE="2026-05-11T23:59:59+08:00"

# Additional Environmental Variables

# TA Email Whitelist (Space separated)
# Any commit by these emails will be SKIPPED by the local test runner
# and EXCLUDED from the official grading target.
TA_EMAILS="jameslee911029@gmail.com chengtingwei190@gmail.com sengerby300@gmail.com"
