# student.conf
# This file is used for TA grading purposes.
# Please fill out your personal information correctly.
# GITHUB_USERNAME must match the account you use to push to GitHub Classroom.

STUDENT_ID="b00000000"
STUDENT_NAME="Your Name"
GITHUB_USERNAME="your-github-id"
